# Generated by Django 4.0.2 on 2022-08-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pronouns',
            field=models.CharField(choices=[('he/him', 'he/him'), ('she/her', 'she/her'), ('they/them', 'they/them'), ('', '')], default='none', max_length=9),
        ),
    ]
