# Generated by Django 4.0.2 on 2022-08-29 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_likes_user_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='message',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
