# Generated by Django 4.0.2 on 2022-08-31 21:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0010_comment_like_count_likedcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='likedcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
