# Generated by Django 4.0.2 on 2022-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='repost_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
