# Generated by Django 4.0.2 on 2022-09-01 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_repost_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reposts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reposts', to='posts.repost'),
        ),
    ]
