# Generated by Django 4.0.2 on 2022-09-01 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_post_reposts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='repost',
            old_name='author',
            new_name='user',
        ),
    ]
