# Generated by Django 4.0.2 on 2022-09-01 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_rename_author_comment_user_rename_author_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='likedcomment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='likedpost',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='repost',
            old_name='user',
            new_name='author',
        ),
    ]
