# Generated by Django 4.0.2 on 2022-09-01 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0018_alter_repost_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='repost_count',
        ),
    ]
