# Generated by Django 4.0.2 on 2022-09-02 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_remove_post_repost_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_post',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='repost',
            name='is_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='repost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repost', to='posts.post'),
        ),
    ]
